# Makefile.deps created Tue Nov 22 15:47:03 PST 2016 by gmake
astree.o: astree.cpp astree.h symtable.h string_set.h lyutils.h auxlib.h \
 yyparse.h
lyutils.o: lyutils.cpp auxlib.h lyutils.h astree.h symtable.h yyparse.h
string_set.o: string_set.cpp string_set.h
auxlib.o: auxlib.cpp auxlib.h
symtable.o: symtable.cpp symtable.h yyparse.h lyutils.h astree.h auxlib.h
symhelper.o: symhelper.cpp astree.h symtable.h string_set.h lyutils.h \
 auxlib.h yyparse.h symhelper.h
main.o: main.cpp string_set.h auxlib.h astree.h symtable.h lyutils.h \
 yyparse.h symhelper.h
yylex.o: yylex.cpp lyutils.h astree.h symtable.h auxlib.h yyparse.h
yyparse.o: yyparse.cpp lyutils.h astree.h symtable.h auxlib.h yyparse.h
