# Makefile.deps created Mon Nov 21 14:00:56 PST 2016 by make
astree.o: astree.cpp astree.h string_set.h lyutils.h auxlib.h yyparse.h
lyutils.o: lyutils.cpp auxlib.h lyutils.h astree.h yyparse.h
string_set.o: string_set.cpp string_set.h
auxlib.o: auxlib.cpp auxlib.h
main.o: main.cpp string_set.h auxlib.h astree.h lyutils.h yyparse.h
yylex.o: yylex.cpp lyutils.h astree.h auxlib.h yyparse.h
yyparse.o: yyparse.cpp lyutils.h astree.h auxlib.h yyparse.h
