#Makefile


lab0: lab0.cpp
	g++ -g -O0 -Wall -Wextra -std=gnu++14 lab0.cpp

myclass.cpp: myclass.cpp
	g++ -g -O0 -Wall -Wextra -std=gnu++14 myclass.cpp

all: lab0.o myclass.o 
	g++ -o lab0 -g -O0 -Wall -Wextra -std=gnu++14 lab0.o myclass.o 


clean:
	rm lab0 *.o
